# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1117, 736)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon = QIcon()
        icon.addFile(u":/icons/images/128.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon()
        icon1.addFile(u":/icons/images/132.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon()
        icon2.addFile(u":/icons/images/SaveFile.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSave_All = QAction(MainWindow)
        self.actionSave_All.setObjectName(u"actionSave_All")
        self.actionImport_Data = QAction(MainWindow)
        self.actionImport_Data.setObjectName(u"actionImport_Data")
        self.actionOutput_Data = QAction(MainWindow)
        self.actionOutput_Data.setObjectName(u"actionOutput_Data")
        self.actionSave_Image = QAction(MainWindow)
        self.actionSave_Image.setObjectName(u"actionSave_Image")
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        icon3 = QIcon()
        icon3.addFile(u":/icons/images/108.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClose.setIcon(icon3)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon4 = QIcon()
        icon4.addFile(u":/icons/images/DELETE.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon5 = QIcon()
        icon5.addFile(u":/icons/images/undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon5)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon6 = QIcon()
        icon6.addFile(u":/icons/images/redo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon6)
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionDelete.setIcon(icon4)
        self.actionFind = QAction(MainWindow)
        self.actionFind.setObjectName(u"actionFind")
        self.actionReplace = QAction(MainWindow)
        self.actionReplace.setObjectName(u"actionReplace")
        self.actionNode_s_Name = QAction(MainWindow)
        self.actionNode_s_Name.setObjectName(u"actionNode_s_Name")
        self.actionEdge_s_Weight = QAction(MainWindow)
        self.actionEdge_s_Weight.setObjectName(u"actionEdge_s_Weight")
        self.actionRedigraph_s_Degrees = QAction(MainWindow)
        self.actionRedigraph_s_Degrees.setObjectName(u"actionRedigraph_s_Degrees")
        self.actionOut_degree = QAction(MainWindow)
        self.actionOut_degree.setObjectName(u"actionOut_degree")
        self.actionIn_degree = QAction(MainWindow)
        self.actionIn_degree.setObjectName(u"actionIn_degree")
        self.actionEasy_Pathway = QAction(MainWindow)
        self.actionEasy_Pathway.setObjectName(u"actionEasy_Pathway")
        self.actionComplicated_Pathway = QAction(MainWindow)
        self.actionComplicated_Pathway.setObjectName(u"actionComplicated_Pathway")
        self.actionEasy_Loop = QAction(MainWindow)
        self.actionEasy_Loop.setObjectName(u"actionEasy_Loop")
        self.actionComplicated_Loop = QAction(MainWindow)
        self.actionComplicated_Loop.setObjectName(u"actionComplicated_Loop")
        self.actionIncidence_Matrix_Undigraph = QAction(MainWindow)
        self.actionIncidence_Matrix_Undigraph.setObjectName(u"actionIncidence_Matrix_Undigraph")
        self.actionBigraph = QAction(MainWindow)
        self.actionBigraph.setObjectName(u"actionBigraph")
        self.actionShortest_Path = QAction(MainWindow)
        self.actionShortest_Path.setObjectName(u"actionShortest_Path")
        self.actionCritical_Path = QAction(MainWindow)
        self.actionCritical_Path.setObjectName(u"actionCritical_Path")
        self.actionFind_Euler_Loop = QAction(MainWindow)
        self.actionFind_Euler_Loop.setObjectName(u"actionFind_Euler_Loop")
        self.actionFind_Hamiltonian_Loop = QAction(MainWindow)
        self.actionFind_Hamiltonian_Loop.setObjectName(u"actionFind_Hamiltonian_Loop")
        self.actionGraph_Coloring_Problem = QAction(MainWindow)
        self.actionGraph_Coloring_Problem.setObjectName(u"actionGraph_Coloring_Problem")
        self.actionDigraph_Mode = QAction(MainWindow)
        self.actionDigraph_Mode.setObjectName(u"actionDigraph_Mode")
        self.actionDigraph_Mode.setCheckable(True)
        self.actionRedigraph_Mode = QAction(MainWindow)
        self.actionRedigraph_Mode.setObjectName(u"actionRedigraph_Mode")
        self.actionRedigraph_Mode.setCheckable(True)
        self.actionMinimise = QAction(MainWindow)
        self.actionMinimise.setObjectName(u"actionMinimise")
        self.actionMaximize = QAction(MainWindow)
        self.actionMaximize.setObjectName(u"actionMaximize")
        self.actionMini_Mode = QAction(MainWindow)
        self.actionMini_Mode.setObjectName(u"actionMini_Mode")
        self.actionHide_ToolBar = QAction(MainWindow)
        self.actionHide_ToolBar.setObjectName(u"actionHide_ToolBar")
        self.actionHide_ToolBar.setCheckable(True)
        self.actionConnect_Author = QAction(MainWindow)
        self.actionConnect_Author.setObjectName(u"actionConnect_Author")
        self.actionWelcome = QAction(MainWindow)
        self.actionWelcome.setObjectName(u"actionWelcome")
        self.actionHelp_Document = QAction(MainWindow)
        self.actionHelp_Document.setObjectName(u"actionHelp_Document")
        self.actionFlie_List = QAction(MainWindow)
        self.actionFlie_List.setObjectName(u"actionFlie_List")
        self.actionPen_Thickness = QAction(MainWindow)
        self.actionPen_Thickness.setObjectName(u"actionPen_Thickness")
        icon7 = QIcon()
        icon7.addFile(u":/icons/images/penStyle.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPen_Thickness.setIcon(icon7)
        self.actionPen_Color = QAction(MainWindow)
        self.actionPen_Color.setObjectName(u"actionPen_Color")
        icon8 = QIcon()
        icon8.addFile(u":/icons/images/penColor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPen_Color.setIcon(icon8)
        self.actionBackground_Color = QAction(MainWindow)
        self.actionBackground_Color.setObjectName(u"actionBackground_Color")
        icon9 = QIcon()
        icon9.addFile(u":/icons/images/backgroundColor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBackground_Color.setIcon(icon9)
        self.actionArc = QAction(MainWindow)
        self.actionArc.setObjectName(u"actionArc")
        icon10 = QIcon()
        icon10.addFile(u":/icons/images/favicon.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.actionArc.setIcon(icon10)
        self.actionCircle = QAction(MainWindow)
        self.actionCircle.setObjectName(u"actionCircle")
        icon11 = QIcon()
        icon11.addFile(u":/icons/images/dot_72px_1154609_easyicon.net.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCircle.setIcon(icon11)
        self.actionSetEnglish = QAction(MainWindow)
        self.actionSetEnglish.setObjectName(u"actionSetEnglish")
        self.actionSetEnglish.setCheckable(True)
        self.actionSetChinese = QAction(MainWindow)
        self.actionSetChinese.setObjectName(u"actionSetChinese")
        self.actionSetChinese.setCheckable(True)
        self.actionAdd_Annotation = QAction(MainWindow)
        self.actionAdd_Annotation.setObjectName(u"actionAdd_Annotation")
        icon12 = QIcon()
        icon12.addFile(u":/icons/images/text_128px_1258351_easyicon.net.ico", QSize(), QIcon.Normal, QIcon.Off)
        icon12.addFile(u":/icons/images/800.bmp", QSize(), QIcon.Normal, QIcon.On)
        self.actionAdd_Annotation.setIcon(icon12)
        self.actionProperty_And_History = QAction(MainWindow)
        self.actionProperty_And_History.setObjectName(u"actionProperty_And_History")
        self.actionProperty_And_History.setCheckable(True)
        self.actionRectangle = QAction(MainWindow)
        self.actionRectangle.setObjectName(u"actionRectangle")
        icon13 = QIcon()
        icon13.addFile(u":/icons/images/Rectangular_marquee_tool_128px_1185795_easyicon.net.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRectangle.setIcon(icon13)
        self.actionAccent_Color = QAction(MainWindow)
        self.actionAccent_Color.setObjectName(u"actionAccent_Color")
        icon14 = QIcon()
        icon14.addFile(u":/icons/images/rt_penColor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAccent_Color.setIcon(icon14)
        self.actionAdjacent_Matrix_Digraph = QAction(MainWindow)
        self.actionAdjacent_Matrix_Digraph.setObjectName(u"actionAdjacent_Matrix_Digraph")
        self.actionReachable_Matrix = QAction(MainWindow)
        self.actionReachable_Matrix.setObjectName(u"actionReachable_Matrix")
        self.actionEdge_Name = QAction(MainWindow)
        self.actionEdge_Name.setObjectName(u"actionEdge_Name")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.verticalLayout_4 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setRenderHints(QPainter.Antialiasing|QPainter.TextAntialiasing)

        self.verticalLayout_4.addWidget(self.graphicsView)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1117, 26))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuRecent_File = QMenu(self.menuFile)
        self.menuRecent_File.setObjectName(u"menuRecent_File")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuFind_or_Replace = QMenu(self.menuEdit)
        self.menuFind_or_Replace.setObjectName(u"menuFind_or_Replace")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuDraw_Tools = QMenu(self.menuSettings)
        self.menuDraw_Tools.setObjectName(u"menuDraw_Tools")
        self.menuLine = QMenu(self.menuDraw_Tools)
        self.menuLine.setObjectName(u"menuLine")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuNodes_Edges_Details = QMenu(self.menuTools)
        self.menuNodes_Edges_Details.setObjectName(u"menuNodes_Edges_Details")
        self.menuNode_s_Degree = QMenu(self.menuNodes_Edges_Details)
        self.menuNode_s_Degree.setObjectName(u"menuNode_s_Degree")
        self.menuDigraph_s_Degrees = QMenu(self.menuNode_s_Degree)
        self.menuDigraph_s_Degrees.setObjectName(u"menuDigraph_s_Degrees")
        self.menuPathway_and_Loop = QMenu(self.menuTools)
        self.menuPathway_and_Loop.setObjectName(u"menuPathway_and_Loop")
        self.menuPathway = QMenu(self.menuPathway_and_Loop)
        self.menuPathway.setObjectName(u"menuPathway")
        self.menuLoop = QMenu(self.menuPathway_and_Loop)
        self.menuLoop.setObjectName(u"menuLoop")
        self.menuGraph_Matrix = QMenu(self.menuTools)
        self.menuGraph_Matrix.setObjectName(u"menuGraph_Matrix")
        self.menuSpecial_Graph = QMenu(self.menuTools)
        self.menuSpecial_Graph.setObjectName(u"menuSpecial_Graph")
        self.menuEuler_Graph = QMenu(self.menuSpecial_Graph)
        self.menuEuler_Graph.setObjectName(u"menuEuler_Graph")
        self.menuHamiltonian_Graph = QMenu(self.menuSpecial_Graph)
        self.menuHamiltonian_Graph.setObjectName(u"menuHamiltonian_Graph")
        self.menuShortest_Path_and_Critical_Path = QMenu(self.menuTools)
        self.menuShortest_Path_and_Critical_Path.setObjectName(u"menuShortest_Path_and_Critical_Path")
        self.menuMode = QMenu(self.menubar)
        self.menuMode.setObjectName(u"menuMode")
        self.menuWinodws = QMenu(self.menubar)
        self.menuWinodws.setObjectName(u"menuWinodws")
        self.menuLanguage = QMenu(self.menuWinodws)
        self.menuLanguage.setObjectName(u"menuLanguage")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.general_utility_toolBar = QToolBar(MainWindow)
        self.general_utility_toolBar.setObjectName(u"general_utility_toolBar")
        MainWindow.addToolBar(Qt.TopToolBarArea, self.general_utility_toolBar)
        self.graphical_toolBar = QToolBar(MainWindow)
        self.graphical_toolBar.setObjectName(u"graphical_toolBar")
        MainWindow.addToolBar(Qt.LeftToolBarArea, self.graphical_toolBar)
        self.dockWidget = QDockWidget(MainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        self.dockWidget.setMinimumSize(QSize(270, 178))
        self.dockWidget.setMaximumSize(QSize(280, 524287))
        self.dockWidget.setAllowedAreas(Qt.LeftDockWidgetArea|Qt.RightDockWidgetArea)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.dockWidgetContents.setMinimumSize(QSize(260, 0))
        self.verticalLayout_2 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.propertyTab = QTabWidget(self.dockWidgetContents)
        self.propertyTab.setObjectName(u"propertyTab")
        self.propertyTab.setMaximumSize(QSize(16777215, 16777215))
        self.propertyTab.setTabPosition(QTabWidget.South)
        self.HistoryTab = QWidget()
        self.HistoryTab.setObjectName(u"HistoryTab")
        self.verticalLayout = QVBoxLayout(self.HistoryTab)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.undoView = QUndoView(self.HistoryTab)
        self.undoView.setObjectName(u"undoView")
        self.undoView.setMinimumSize(QSize(0, 0))
        self.undoView.setMaximumSize(QSize(265, 16777215))

        self.verticalLayout.addWidget(self.undoView)

        self.propertyTab.addTab(self.HistoryTab, "")
        self.DetailsTab = QWidget()
        self.DetailsTab.setObjectName(u"DetailsTab")
        self.verticalLayout_3 = QVBoxLayout(self.DetailsTab)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.GraphDetails = QListView(self.DetailsTab)
        self.GraphDetails.setObjectName(u"GraphDetails")
        self.GraphDetails.setMinimumSize(QSize(0, 0))
        self.GraphDetails.setMaximumSize(QSize(16777215, 16777215))

        self.verticalLayout_3.addWidget(self.GraphDetails)

        self.propertyTab.addTab(self.DetailsTab, "")

        self.verticalLayout_2.addWidget(self.propertyTab)

        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.dockWidget)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuWinodws.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuRecent_File.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addAction(self.actionSave_All)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImport_Data)
        self.menuFile.addAction(self.actionOutput_Data)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuRecent_File.addAction(self.actionFlie_List)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionDelete)
        self.menuEdit.addAction(self.menuFind_or_Replace.menuAction())
        self.menuFind_or_Replace.addAction(self.actionFind)
        self.menuFind_or_Replace.addAction(self.actionReplace)
        self.menuSettings.addAction(self.menuDraw_Tools.menuAction())
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionPen_Thickness)
        self.menuSettings.addAction(self.actionPen_Color)
        self.menuSettings.addAction(self.actionBackground_Color)
        self.menuSettings.addAction(self.actionAccent_Color)
        self.menuSettings.addAction(self.actionProperty_And_History)
        self.menuDraw_Tools.addAction(self.menuLine.menuAction())
        self.menuDraw_Tools.addAction(self.actionCircle)
        self.menuDraw_Tools.addAction(self.actionRectangle)
        self.menuLine.addAction(self.actionArc)
        self.menuTools.addAction(self.menuNodes_Edges_Details.menuAction())
        self.menuTools.addAction(self.menuPathway_and_Loop.menuAction())
        self.menuTools.addAction(self.menuGraph_Matrix.menuAction())
        self.menuTools.addAction(self.menuSpecial_Graph.menuAction())
        self.menuTools.addAction(self.menuShortest_Path_and_Critical_Path.menuAction())
        self.menuTools.addAction(self.actionGraph_Coloring_Problem)
        self.menuNodes_Edges_Details.addAction(self.actionNode_s_Name)
        self.menuNodes_Edges_Details.addAction(self.actionEdge_Name)
        self.menuNodes_Edges_Details.addAction(self.actionEdge_s_Weight)
        self.menuNodes_Edges_Details.addAction(self.menuNode_s_Degree.menuAction())
        self.menuNode_s_Degree.addAction(self.menuDigraph_s_Degrees.menuAction())
        self.menuNode_s_Degree.addAction(self.actionRedigraph_s_Degrees)
        self.menuDigraph_s_Degrees.addAction(self.actionOut_degree)
        self.menuDigraph_s_Degrees.addAction(self.actionIn_degree)
        self.menuPathway_and_Loop.addAction(self.menuPathway.menuAction())
        self.menuPathway_and_Loop.addAction(self.menuLoop.menuAction())
        self.menuPathway.addAction(self.actionEasy_Pathway)
        self.menuPathway.addAction(self.actionComplicated_Pathway)
        self.menuLoop.addAction(self.actionEasy_Loop)
        self.menuLoop.addAction(self.actionComplicated_Loop)
        self.menuGraph_Matrix.addAction(self.actionIncidence_Matrix_Undigraph)
        self.menuGraph_Matrix.addAction(self.actionAdjacent_Matrix_Digraph)
        self.menuGraph_Matrix.addAction(self.actionReachable_Matrix)
        self.menuSpecial_Graph.addAction(self.actionBigraph)
        self.menuSpecial_Graph.addAction(self.menuEuler_Graph.menuAction())
        self.menuSpecial_Graph.addAction(self.menuHamiltonian_Graph.menuAction())
        self.menuEuler_Graph.addAction(self.actionFind_Euler_Loop)
        self.menuHamiltonian_Graph.addAction(self.actionFind_Hamiltonian_Loop)
        self.menuShortest_Path_and_Critical_Path.addAction(self.actionShortest_Path)
        self.menuShortest_Path_and_Critical_Path.addAction(self.actionCritical_Path)
        self.menuMode.addAction(self.actionRedigraph_Mode)
        self.menuMode.addAction(self.actionDigraph_Mode)
        self.menuWinodws.addAction(self.actionMinimise)
        self.menuWinodws.addAction(self.actionMaximize)
        self.menuWinodws.addAction(self.actionMini_Mode)
        self.menuWinodws.addAction(self.actionHide_ToolBar)
        self.menuWinodws.addAction(self.menuLanguage.menuAction())
        self.menuLanguage.addAction(self.actionSetEnglish)
        self.menuLanguage.addAction(self.actionSetChinese)
        self.menuHelp.addAction(self.actionConnect_Author)
        self.menuHelp.addAction(self.actionWelcome)
        self.menuHelp.addAction(self.actionHelp_Document)
        self.general_utility_toolBar.addAction(self.actionNew)
        self.general_utility_toolBar.addAction(self.actionOpen)
        self.general_utility_toolBar.addAction(self.actionSave)
        self.general_utility_toolBar.addAction(self.actionUndo)
        self.general_utility_toolBar.addAction(self.actionRedo)
        self.general_utility_toolBar.addAction(self.actionDelete)
        self.general_utility_toolBar.addSeparator()
        self.general_utility_toolBar.addAction(self.actionPen_Color)
        self.general_utility_toolBar.addAction(self.actionPen_Thickness)
        self.general_utility_toolBar.addAction(self.actionBackground_Color)
        self.general_utility_toolBar.addAction(self.actionAccent_Color)
        self.graphical_toolBar.addAction(self.actionArc)
        self.graphical_toolBar.addAction(self.actionCircle)
        self.graphical_toolBar.addAction(self.actionRectangle)
        self.graphical_toolBar.addAction(self.actionAdd_Annotation)

        self.retranslateUi(MainWindow)
        self.actionHide_ToolBar.triggered.connect(self.general_utility_toolBar.hide)
        self.actionHide_ToolBar.triggered.connect(self.graphical_toolBar.hide)
        self.actionMinimise.triggered.connect(MainWindow.showMinimized)
        self.actionMaximize.triggered.connect(MainWindow.showMaximized)

        self.propertyTab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionNew.setStatusTip(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u6587\u4ef6", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.actionOpen.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionOpen.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave.setStatusTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6587\u4ef6", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a", None))
#if QT_CONFIG(tooltip)
        self.actionSave_As.setToolTip(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave_As.setStatusTip(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a", None))
#endif // QT_CONFIG(statustip)
        self.actionSave_All.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u5168\u90e8", None))
#if QT_CONFIG(tooltip)
        self.actionSave_All.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u5168\u90e8", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave_All.setStatusTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6240\u6709", None))
#endif // QT_CONFIG(statustip)
        self.actionImport_Data.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u6570\u636e", None))
#if QT_CONFIG(tooltip)
        self.actionImport_Data.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u6570\u636e", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionImport_Data.setStatusTip(QCoreApplication.translate("MainWindow", u" \u5bfc\u51fa\u56fe\u6570\u636e", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionImport_Data.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionOutput_Data.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u6570\u636e", None))
#if QT_CONFIG(tooltip)
        self.actionOutput_Data.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u6570\u636e", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionOutput_Data.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u56fe\u6570\u636e", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionOutput_Data.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_Image.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u4e3a\u56fe\u7247", None))
#if QT_CONFIG(tooltip)
        self.actionSave_Image.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u4e3a\u56fe\u7247", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave_Image.setStatusTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u4e3a\u56fe\u7247", None))
#endif // QT_CONFIG(statustip)
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.actionClose.setToolTip(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionClose.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u5f53\u524d\u7a97\u53e3", None))
#endif // QT_CONFIG(statustip)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa\u5e94\u7528", None))
#if QT_CONFIG(tooltip)
        self.actionQuit.setToolTip(QCoreApplication.translate("MainWindow", u"\u9000\u51fa\u5e94\u7528", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionQuit.setStatusTip(QCoreApplication.translate("MainWindow", u"\u9000\u51fa\u5e94\u7528\u7a0b\u5e8f", None))
#endif // QT_CONFIG(statustip)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"\u64a4\u9500", None))
#if QT_CONFIG(tooltip)
        self.actionUndo.setToolTip(QCoreApplication.translate("MainWindow", u"\u64a4\u9500", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
#if QT_CONFIG(tooltip)
        self.actionRedo.setToolTip(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
#if QT_CONFIG(tooltip)
        self.actionDelete.setToolTip(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionDelete.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.actionFind.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627e", None))
#if QT_CONFIG(tooltip)
        self.actionFind.setToolTip(QCoreApplication.translate("MainWindow", u"\u67e5\u627e", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionFind.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionReplace.setText(QCoreApplication.translate("MainWindow", u"\u66ff\u6362", None))
#if QT_CONFIG(tooltip)
        self.actionReplace.setToolTip(QCoreApplication.translate("MainWindow", u"\u66ff\u6362", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionReplace.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionNode_s_Name.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u70b9\u540d\u79f0", None))
#if QT_CONFIG(tooltip)
        self.actionNode_s_Name.setToolTip(QCoreApplication.translate("MainWindow", u"\u7ed3\u70b9\u540d\u79f0", None))
#endif // QT_CONFIG(tooltip)
        self.actionEdge_s_Weight.setText(QCoreApplication.translate("MainWindow", u"\u8fb9\u7684\u6743\u91cd", None))
#if QT_CONFIG(tooltip)
        self.actionEdge_s_Weight.setToolTip(QCoreApplication.translate("MainWindow", u"\u8fb9\u7684\u6743\u91cd", None))
#endif // QT_CONFIG(tooltip)
        self.actionRedigraph_s_Degrees.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u70b9\u5ea6", None))
#if QT_CONFIG(tooltip)
        self.actionRedigraph_s_Degrees.setToolTip(QCoreApplication.translate("MainWindow", u"\u7ed3\u70b9\u5ea6", None))
#endif // QT_CONFIG(tooltip)
        self.actionOut_degree.setText(QCoreApplication.translate("MainWindow", u"\u51fa\u5ea6", None))
#if QT_CONFIG(tooltip)
        self.actionOut_degree.setToolTip(QCoreApplication.translate("MainWindow", u"\u51fa\u5ea6", None))
#endif // QT_CONFIG(tooltip)
        self.actionIn_degree.setText(QCoreApplication.translate("MainWindow", u"\u5165\u5ea6", None))
#if QT_CONFIG(tooltip)
        self.actionIn_degree.setToolTip(QCoreApplication.translate("MainWindow", u"\u5165\u5ea6", None))
#endif // QT_CONFIG(tooltip)
        self.actionEasy_Pathway.setText(QCoreApplication.translate("MainWindow", u"\u7b80\u5355\u901a\u8def", None))
#if QT_CONFIG(tooltip)
        self.actionEasy_Pathway.setToolTip(QCoreApplication.translate("MainWindow", u"\u7b80\u5355\u901a\u8def", None))
#endif // QT_CONFIG(tooltip)
        self.actionComplicated_Pathway.setText(QCoreApplication.translate("MainWindow", u"\u590d\u6742\u901a\u8def", None))
#if QT_CONFIG(tooltip)
        self.actionComplicated_Pathway.setToolTip(QCoreApplication.translate("MainWindow", u"\u590d\u6742\u901a\u8def", None))
#endif // QT_CONFIG(tooltip)
        self.actionEasy_Loop.setText(QCoreApplication.translate("MainWindow", u"\u7b80\u5355\u56de\u8def", None))
#if QT_CONFIG(tooltip)
        self.actionEasy_Loop.setToolTip(QCoreApplication.translate("MainWindow", u"\u7b80\u5355\u56de\u8def", None))
#endif // QT_CONFIG(tooltip)
        self.actionComplicated_Loop.setText(QCoreApplication.translate("MainWindow", u"\u590d\u6742\u56de\u8def", None))
#if QT_CONFIG(tooltip)
        self.actionComplicated_Loop.setToolTip(QCoreApplication.translate("MainWindow", u"\u590d\u6742\u56de\u8def", None))
#endif // QT_CONFIG(tooltip)
        self.actionIncidence_Matrix_Undigraph.setText(QCoreApplication.translate("MainWindow", u"\u5173\u8054\u77e9\u9635", None))
#if QT_CONFIG(tooltip)
        self.actionIncidence_Matrix_Undigraph.setToolTip(QCoreApplication.translate("MainWindow", u"\u5173\u8054\u77e9\u9635", None))
#endif // QT_CONFIG(tooltip)
        self.actionBigraph.setText(QCoreApplication.translate("MainWindow", u"\u4e8c\u90e8\u56fe", None))
#if QT_CONFIG(tooltip)
        self.actionBigraph.setToolTip(QCoreApplication.translate("MainWindow", u"\u4e8c\u90e8\u56fe", None))
#endif // QT_CONFIG(tooltip)
        self.actionShortest_Path.setText(QCoreApplication.translate("MainWindow", u"\u6700\u77ed\u8def\u5f84", None))
#if QT_CONFIG(tooltip)
        self.actionShortest_Path.setToolTip(QCoreApplication.translate("MainWindow", u"\u6700\u77ed\u8def\u5f84", None))
#endif // QT_CONFIG(tooltip)
        self.actionCritical_Path.setText(QCoreApplication.translate("MainWindow", u"\u5173\u952e\u8def\u5f84", None))
#if QT_CONFIG(tooltip)
        self.actionCritical_Path.setToolTip(QCoreApplication.translate("MainWindow", u"\u5173\u952e\u8def\u5f84", None))
#endif // QT_CONFIG(tooltip)
        self.actionFind_Euler_Loop.setText(QCoreApplication.translate("MainWindow", u"\u5bfb\u627e\u6b27\u62c9\u56de\u8def", None))
#if QT_CONFIG(tooltip)
        self.actionFind_Euler_Loop.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bfb\u627e\u6b27\u62c9\u56de\u8def", None))
#endif // QT_CONFIG(tooltip)
        self.actionFind_Hamiltonian_Loop.setText(QCoreApplication.translate("MainWindow", u"\u5bfb\u627e\u54c8\u5bc6\u987f\u56de\u8def", None))
#if QT_CONFIG(tooltip)
        self.actionFind_Hamiltonian_Loop.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bfb\u627e\u54c8\u5bc6\u987f\u56de\u8def", None))
#endif // QT_CONFIG(tooltip)
        self.actionGraph_Coloring_Problem.setText(QCoreApplication.translate("MainWindow", u"\u7740\u8272\u95ee\u9898", None))
#if QT_CONFIG(tooltip)
        self.actionGraph_Coloring_Problem.setToolTip(QCoreApplication.translate("MainWindow", u"\u7740\u8272\u95ee\u9898", None))
#endif // QT_CONFIG(tooltip)
        self.actionDigraph_Mode.setText(QCoreApplication.translate("MainWindow", u"\u6709\u5411\u56fe\u6a21\u5f0f", None))
#if QT_CONFIG(tooltip)
        self.actionDigraph_Mode.setToolTip(QCoreApplication.translate("MainWindow", u"\u6709\u5411\u56fe\u6a21\u5f0f", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionDigraph_Mode.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedigraph_Mode.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u5411\u56fe\u6a21\u5f0f", None))
#if QT_CONFIG(tooltip)
        self.actionRedigraph_Mode.setToolTip(QCoreApplication.translate("MainWindow", u"\u65e0\u5411\u56fe\u6a21\u5f0f", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionRedigraph_Mode.setShortcut(QCoreApplication.translate("MainWindow", u"F2", None))
#endif // QT_CONFIG(shortcut)
        self.actionMinimise.setText(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3\u6700\u5c0f\u5316", None))
#if QT_CONFIG(tooltip)
        self.actionMinimise.setToolTip(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3\u6700\u5c0f\u5316", None))
#endif // QT_CONFIG(tooltip)
        self.actionMaximize.setText(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3\u6700\u5927\u5316", None))
#if QT_CONFIG(tooltip)
        self.actionMaximize.setToolTip(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3\u6700\u5927\u5316", None))
#endif // QT_CONFIG(tooltip)
        self.actionMini_Mode.setText(QCoreApplication.translate("MainWindow", u"\u8ff7\u4f60\u6a21\u5f0f", None))
#if QT_CONFIG(tooltip)
        self.actionMini_Mode.setToolTip(QCoreApplication.translate("MainWindow", u"\u8ff7\u4f60\u6a21\u5f0f", None))
#endif // QT_CONFIG(tooltip)
        self.actionHide_ToolBar.setText(QCoreApplication.translate("MainWindow", u"\u9690\u85cf\u5de5\u5177\u680f", None))
#if QT_CONFIG(tooltip)
        self.actionHide_ToolBar.setToolTip(QCoreApplication.translate("MainWindow", u"\u9690\u85cf\u5de5\u5177\u680f", None))
#endif // QT_CONFIG(tooltip)
        self.actionConnect_Author.setText(QCoreApplication.translate("MainWindow", u"\u8054\u7cfb\u4f5c\u8005", None))
#if QT_CONFIG(tooltip)
        self.actionConnect_Author.setToolTip(QCoreApplication.translate("MainWindow", u"\u8054\u7cfb\u4f5c\u8005", None))
#endif // QT_CONFIG(tooltip)
        self.actionWelcome.setText(QCoreApplication.translate("MainWindow", u"\u6b22\u8fce", None))
#if QT_CONFIG(tooltip)
        self.actionWelcome.setToolTip(QCoreApplication.translate("MainWindow", u"\u6b22\u8fce", None))
#endif // QT_CONFIG(tooltip)
        self.actionHelp_Document.setText(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9\u6587\u6863", None))
#if QT_CONFIG(tooltip)
        self.actionHelp_Document.setToolTip(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9\u6587\u6863", None))
#endif // QT_CONFIG(tooltip)
        self.actionFlie_List.setText(QCoreApplication.translate("MainWindow", u"\u6700\u8fd1\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.actionFlie_List.setToolTip(QCoreApplication.translate("MainWindow", u"\u6700\u8fd1\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
        self.actionPen_Thickness.setText(QCoreApplication.translate("MainWindow", u"\u753b\u7b14\u7c97\u7ec6\u4e0e\u6837\u5f0f", None))
#if QT_CONFIG(tooltip)
        self.actionPen_Thickness.setToolTip(QCoreApplication.translate("MainWindow", u"\u753b\u7b14\u7c97\u7ec6\u4e0e\u6837\u5f0f", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionPen_Thickness.setStatusTip(QCoreApplication.translate("MainWindow", u"\u753b\u7b14\u7c97\u7ec6\u4e0e\u6837\u5f0f", None))
#endif // QT_CONFIG(statustip)
        self.actionPen_Color.setText(QCoreApplication.translate("MainWindow", u"\u753b\u7b14\u989c\u8272", None))
#if QT_CONFIG(tooltip)
        self.actionPen_Color.setToolTip(QCoreApplication.translate("MainWindow", u"\u753b\u7b14\u989c\u8272", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionPen_Color.setStatusTip(QCoreApplication.translate("MainWindow", u"\u753b\u7b14\u989c\u8272", None))
#endif // QT_CONFIG(statustip)
        self.actionBackground_Color.setText(QCoreApplication.translate("MainWindow", u"\u80cc\u666f\u8272", None))
#if QT_CONFIG(tooltip)
        self.actionBackground_Color.setToolTip(QCoreApplication.translate("MainWindow", u"\u80cc\u666f\u8272", None))
#endif // QT_CONFIG(tooltip)
        self.actionArc.setText(QCoreApplication.translate("MainWindow", u"\u66f2\u7ebf", None))
#if QT_CONFIG(tooltip)
        self.actionArc.setToolTip(QCoreApplication.translate("MainWindow", u"\u66f2\u7ebf", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionArc.setStatusTip(QCoreApplication.translate("MainWindow", u"\u66f2\u7ebf", None))
#endif // QT_CONFIG(statustip)
        self.actionCircle.setText(QCoreApplication.translate("MainWindow", u"\u7ed3\u70b9", None))
#if QT_CONFIG(tooltip)
        self.actionCircle.setToolTip(QCoreApplication.translate("MainWindow", u"\u7ed3\u70b9", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionCircle.setStatusTip(QCoreApplication.translate("MainWindow", u"\u7ed3\u70b9", None))
#endif // QT_CONFIG(statustip)
        self.actionSetEnglish.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionSetChinese.setText(QCoreApplication.translate("MainWindow", u"\u4e2d\u6587", None))
#if QT_CONFIG(tooltip)
        self.actionSetChinese.setToolTip(QCoreApplication.translate("MainWindow", u"\u4e2d\u6587", None))
#endif // QT_CONFIG(tooltip)
        self.actionAdd_Annotation.setText(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0\u6ce8\u91ca", None))
#if QT_CONFIG(tooltip)
        self.actionAdd_Annotation.setToolTip(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0\u6ce8\u91ca", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionAdd_Annotation.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6587\u672c", None))
#endif // QT_CONFIG(statustip)
        self.actionProperty_And_History.setText(QCoreApplication.translate("MainWindow", u"\u5c5e\u6027\u4e0e\u5386\u53f2\u8bb0\u5f55", None))
#if QT_CONFIG(tooltip)
        self.actionProperty_And_History.setToolTip(QCoreApplication.translate("MainWindow", u"\u5c5e\u6027\u4e0e\u5386\u53f2\u8bb0\u5f55", None))
#endif // QT_CONFIG(tooltip)
        self.actionRectangle.setText(QCoreApplication.translate("MainWindow", u"\u77e9\u5f62", None))
#if QT_CONFIG(tooltip)
        self.actionRectangle.setToolTip(QCoreApplication.translate("MainWindow", u"\u77e9\u5f62", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionRectangle.setStatusTip(QCoreApplication.translate("MainWindow", u"\u77e9\u5f62\u6846", None))
#endif // QT_CONFIG(statustip)
        self.actionAccent_Color.setText(QCoreApplication.translate("MainWindow", u"\u9009\u4e2d\u8272", None))
#if QT_CONFIG(tooltip)
        self.actionAccent_Color.setToolTip(QCoreApplication.translate("MainWindow", u"\u5f3a\u8c03\u8272", None))
#endif // QT_CONFIG(tooltip)
        self.actionAdjacent_Matrix_Digraph.setText(QCoreApplication.translate("MainWindow", u"\u90bb\u63a5\u77e9\u9635", None))
        self.actionReachable_Matrix.setText(QCoreApplication.translate("MainWindow", u"\u53ef\u8fbe\u77e9\u9635", None))
        self.actionEdge_Name.setText(QCoreApplication.translate("MainWindow", u"\u8fb9\u540d\u79f0", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u" \u6587\u4ef6", None))
        self.menuRecent_File.setTitle(QCoreApplication.translate("MainWindow", u" \u6700\u8fd1\u6253\u5f00\u7684\u6587\u4ef6", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
        self.menuFind_or_Replace.setTitle(QCoreApplication.translate("MainWindow", u"\u67e5\u627e/\u66ff\u6362", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
        self.menuDraw_Tools.setTitle(QCoreApplication.translate("MainWindow", u"\u7ed8\u56fe\u5de5\u5177", None))
        self.menuLine.setTitle(QCoreApplication.translate("MainWindow", u"\u7ebf", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"\u5de5\u5177", None))
        self.menuNodes_Edges_Details.setTitle(QCoreApplication.translate("MainWindow", u"\u7ed3\u70b9\u4e0e\u8fb9\u8be6\u60c5", None))
        self.menuNode_s_Degree.setTitle(QCoreApplication.translate("MainWindow", u"\u7ed3\u70b9\u7684\u5ea6", None))
        self.menuDigraph_s_Degrees.setTitle(QCoreApplication.translate("MainWindow", u"\u6709\u5411\u56fe\u7684\u5ea6", None))
        self.menuPathway_and_Loop.setTitle(QCoreApplication.translate("MainWindow", u"\u901a\u8def\u548c\u56de\u8def", None))
        self.menuPathway.setTitle(QCoreApplication.translate("MainWindow", u" \u901a\u8def", None))
        self.menuLoop.setTitle(QCoreApplication.translate("MainWindow", u" \u56de\u8def", None))
        self.menuGraph_Matrix.setTitle(QCoreApplication.translate("MainWindow", u"\u56fe\u7684\u77e9\u9635", None))
        self.menuSpecial_Graph.setTitle(QCoreApplication.translate("MainWindow", u"\u7279\u6b8a\u56fe", None))
        self.menuEuler_Graph.setTitle(QCoreApplication.translate("MainWindow", u"\u6b27\u62c9\u56fe", None))
        self.menuHamiltonian_Graph.setTitle(QCoreApplication.translate("MainWindow", u"\u54c8\u5bc6\u987f\u56fe", None))
        self.menuShortest_Path_and_Critical_Path.setTitle(QCoreApplication.translate("MainWindow", u"\u6700\u77ed\u8def\u5f84\u548c\u5173\u952e\u8def\u5f84", None))
        self.menuMode.setTitle(QCoreApplication.translate("MainWindow", u"\u6a21\u5f0f", None))
        self.menuWinodws.setTitle(QCoreApplication.translate("MainWindow", u" \u7a97\u53e3", None))
        self.menuLanguage.setTitle(QCoreApplication.translate("MainWindow", u" \u8bed\u8a00", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u" \u5e2e\u52a9", None))
        self.general_utility_toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"  \u5e38\u89c4\u529f\u80fd", None))
        self.graphical_toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u" \u7ed8\u56fe\u5de5\u5177", None))
        self.propertyTab.setTabText(self.propertyTab.indexOf(self.HistoryTab), QCoreApplication.translate("MainWindow", u"\u5386\u53f2\u8bb0\u5f55", None))
        self.propertyTab.setTabText(self.propertyTab.indexOf(self.DetailsTab), QCoreApplication.translate("MainWindow", u"\u7ed8\u56fe\u8be6\u60c5", None))
    # retranslateUi

