# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MainWindow.ui'
##
## Created by: Qt User Interface Compiler version 5.14.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QMetaObject,
    QObject, QPoint, QRect, QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter,
    QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

import res_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1117, 736)
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        icon = QIcon()
        icon.addFile(u":/icons/images/128.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actionNew.setIcon(icon)
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        icon1 = QIcon()
        icon1.addFile(u":/icons/images/132.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon2 = QIcon()
        icon2.addFile(u":/icons/images/SaveFile.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon2)
        self.actionSave_As = QAction(MainWindow)
        self.actionSave_As.setObjectName(u"actionSave_As")
        self.actionSave_All = QAction(MainWindow)
        self.actionSave_All.setObjectName(u"actionSave_All")
        self.actionSave_All.setEnabled(False)
        self.actionImportData = QAction(MainWindow)
        self.actionImportData.setObjectName(u"actionImportData")
        self.actionImportData.setEnabled(True)
        self.actionOutputData = QAction(MainWindow)
        self.actionOutputData.setObjectName(u"actionOutputData")
        self.actionOutputData.setEnabled(True)
        self.actionSave_Image = QAction(MainWindow)
        self.actionSave_Image.setObjectName(u"actionSave_Image")
        self.actionSave_Image.setEnabled(False)
        self.actionClose = QAction(MainWindow)
        self.actionClose.setObjectName(u"actionClose")
        self.actionClose.setEnabled(False)
        icon3 = QIcon()
        icon3.addFile(u":/icons/images/108.bmp", QSize(), QIcon.Normal, QIcon.Off)
        self.actionClose.setIcon(icon3)
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon4 = QIcon()
        icon4.addFile(u":/icons/images/DELETE.BMP", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuit.setIcon(icon4)
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon5 = QIcon()
        icon5.addFile(u":/icons/images/undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon5)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon6 = QIcon()
        icon6.addFile(u":/icons/images/redo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon6)
        self.actionDelete = QAction(MainWindow)
        self.actionDelete.setObjectName(u"actionDelete")
        self.actionDelete.setIcon(icon4)
        self.actionFind = QAction(MainWindow)
        self.actionFind.setObjectName(u"actionFind")
        self.actionReplace = QAction(MainWindow)
        self.actionReplace.setObjectName(u"actionReplace")
        self.actionEasy_Pathway = QAction(MainWindow)
        self.actionEasy_Pathway.setObjectName(u"actionEasy_Pathway")
        self.actionEasy_Loop = QAction(MainWindow)
        self.actionEasy_Loop.setObjectName(u"actionEasy_Loop")
        self.actionIncidence_Matrix_Undigraph = QAction(MainWindow)
        self.actionIncidence_Matrix_Undigraph.setObjectName(u"actionIncidence_Matrix_Undigraph")
        self.actionCritical_Path = QAction(MainWindow)
        self.actionCritical_Path.setObjectName(u"actionCritical_Path")
        self.actionGraph_Coloring_Problem = QAction(MainWindow)
        self.actionGraph_Coloring_Problem.setObjectName(u"actionGraph_Coloring_Problem")
        self.actionDigraph_Mode = QAction(MainWindow)
        self.actionDigraph_Mode.setObjectName(u"actionDigraph_Mode")
        self.actionDigraph_Mode.setCheckable(True)
        self.actionDigraph_Mode.setChecked(True)
        self.actionRedigraph_Mode = QAction(MainWindow)
        self.actionRedigraph_Mode.setObjectName(u"actionRedigraph_Mode")
        self.actionRedigraph_Mode.setCheckable(True)
        self.actionMinimise = QAction(MainWindow)
        self.actionMinimise.setObjectName(u"actionMinimise")
        self.actionMaximize = QAction(MainWindow)
        self.actionMaximize.setObjectName(u"actionMaximize")
        self.actionMini_Mode = QAction(MainWindow)
        self.actionMini_Mode.setObjectName(u"actionMini_Mode")
        self.actionHide_ToolBar = QAction(MainWindow)
        self.actionHide_ToolBar.setObjectName(u"actionHide_ToolBar")
        self.actionHide_ToolBar.setCheckable(True)
        self.actionHide_ToolBar.setChecked(True)
        self.actionConnect_Author = QAction(MainWindow)
        self.actionConnect_Author.setObjectName(u"actionConnect_Author")
        self.actionWelcome = QAction(MainWindow)
        self.actionWelcome.setObjectName(u"actionWelcome")
        self.actionHelp_Document = QAction(MainWindow)
        self.actionHelp_Document.setObjectName(u"actionHelp_Document")
        self.actionFlie_List = QAction(MainWindow)
        self.actionFlie_List.setObjectName(u"actionFlie_List")
        self.actionPen_Thickness = QAction(MainWindow)
        self.actionPen_Thickness.setObjectName(u"actionPen_Thickness")
        self.actionPen_Thickness.setEnabled(False)
        icon7 = QIcon()
        icon7.addFile(u":/icons/images/penStyle.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPen_Thickness.setIcon(icon7)
        self.actionPen_Color = QAction(MainWindow)
        self.actionPen_Color.setObjectName(u"actionPen_Color")
        self.actionPen_Color.setEnabled(False)
        icon8 = QIcon()
        icon8.addFile(u":/icons/images/penColor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionPen_Color.setIcon(icon8)
        self.actionBackground_Color = QAction(MainWindow)
        self.actionBackground_Color.setObjectName(u"actionBackground_Color")
        self.actionBackground_Color.setEnabled(False)
        icon9 = QIcon()
        icon9.addFile(u":/icons/images/backgroundColor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionBackground_Color.setIcon(icon9)
        self.actionArc = QAction(MainWindow)
        self.actionArc.setObjectName(u"actionArc")
        icon10 = QIcon()
        icon10.addFile(u":/icons/images/favicon.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.actionArc.setIcon(icon10)
        self.actionCircle = QAction(MainWindow)
        self.actionCircle.setObjectName(u"actionCircle")
        icon11 = QIcon()
        icon11.addFile(u":/icons/images/dot_72px_1154609_easyicon.net.ico", QSize(), QIcon.Normal, QIcon.Off)
        self.actionCircle.setIcon(icon11)
        self.actionSetEnglish = QAction(MainWindow)
        self.actionSetEnglish.setObjectName(u"actionSetEnglish")
        self.actionSetEnglish.setCheckable(True)
        self.actionSetChinese = QAction(MainWindow)
        self.actionSetChinese.setObjectName(u"actionSetChinese")
        self.actionSetChinese.setCheckable(True)
        self.actionAdd_Annotation = QAction(MainWindow)
        self.actionAdd_Annotation.setObjectName(u"actionAdd_Annotation")
        icon12 = QIcon()
        icon12.addFile(u":/icons/images/text_128px_1258351_easyicon.net.ico", QSize(), QIcon.Normal, QIcon.Off)
        icon12.addFile(u":/icons/images/800.bmp", QSize(), QIcon.Normal, QIcon.On)
        self.actionAdd_Annotation.setIcon(icon12)
        self.actionProperty_And_History = QAction(MainWindow)
        self.actionProperty_And_History.setObjectName(u"actionProperty_And_History")
        self.actionProperty_And_History.setCheckable(True)
        self.actionProperty_And_History.setChecked(True)
        self.actionAccent_Color = QAction(MainWindow)
        self.actionAccent_Color.setObjectName(u"actionAccent_Color")
        self.actionAccent_Color.setEnabled(False)
        icon13 = QIcon()
        icon13.addFile(u":/icons/images/rt_penColor.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionAccent_Color.setIcon(icon13)
        self.actionReachable_Matrix = QAction(MainWindow)
        self.actionReachable_Matrix.setObjectName(u"actionReachable_Matrix")
        self.actionPrimary_Pathway = QAction(MainWindow)
        self.actionPrimary_Pathway.setObjectName(u"actionPrimary_Pathway")
        self.actionPrimary_Loop = QAction(MainWindow)
        self.actionPrimary_Loop.setObjectName(u"actionPrimary_Loop")
        self.actionShortestPath = QAction(MainWindow)
        self.actionShortestPath.setObjectName(u"actionShortestPath")
        self.actionWeight = QAction(MainWindow)
        self.actionWeight.setObjectName(u"actionWeight")
        self.action_EdgeNum = QAction(MainWindow)
        self.action_EdgeNum.setObjectName(u"action_EdgeNum")
        self.actionConnectivity = QAction(MainWindow)
        self.actionConnectivity.setObjectName(u"actionConnectivity")
        self.actionCompleteGraph = QAction(MainWindow)
        self.actionCompleteGraph.setObjectName(u"actionCompleteGraph")
        self.actionMultipleOrSimple = QAction(MainWindow)
        self.actionMultipleOrSimple.setObjectName(u"actionMultipleOrSimple")
        self.actionShowNodesWeight = QAction(MainWindow)
        self.actionShowNodesWeight.setObjectName(u"actionShowNodesWeight")
        self.actionShowNodesWeight.setCheckable(True)
        self.actionShowEdgesWeight = QAction(MainWindow)
        self.actionShowEdgesWeight.setObjectName(u"actionShowEdgesWeight")
        self.actionShowEdgesWeight.setCheckable(True)
        self.actionHideControlPoint = QAction(MainWindow)
        self.actionHideControlPoint.setObjectName(u"actionHideControlPoint")
        self.actionHideControlPoint.setCheckable(True)
        self.actionHideControlPoint.setChecked(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout = QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.Page = QWidget()
        self.Page.setObjectName(u"Page")
        self.tabWidget.addTab(self.Page, "")

        self.horizontalLayout.addWidget(self.tabWidget)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1117, 26))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuRecent_File = QMenu(self.menuFile)
        self.menuRecent_File.setObjectName(u"menuRecent_File")
        self.menuRecent_File.setEnabled(False)
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuDraw_Tools = QMenu(self.menuSettings)
        self.menuDraw_Tools.setObjectName(u"menuDraw_Tools")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuLoop = QMenu(self.menuTools)
        self.menuLoop.setObjectName(u"menuLoop")
        self.menuGraph_Matrix = QMenu(self.menuTools)
        self.menuGraph_Matrix.setObjectName(u"menuGraph_Matrix")
        self.menu = QMenu(self.menuGraph_Matrix)
        self.menu.setObjectName(u"menu")
        self.menuPathway = QMenu(self.menuTools)
        self.menuPathway.setObjectName(u"menuPathway")
        self.menuShow_Weight = QMenu(self.menuTools)
        self.menuShow_Weight.setObjectName(u"menuShow_Weight")
        self.menuMode = QMenu(self.menubar)
        self.menuMode.setObjectName(u"menuMode")
        self.menuWinodws = QMenu(self.menubar)
        self.menuWinodws.setObjectName(u"menuWinodws")
        self.menuLanguage = QMenu(self.menuWinodws)
        self.menuLanguage.setObjectName(u"menuLanguage")
        self.menuHelp = QMenu(self.menubar)
        self.menuHelp.setObjectName(u"menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.general_utility_toolBar = QToolBar(MainWindow)
        self.general_utility_toolBar.setObjectName(u"general_utility_toolBar")
        self.general_utility_toolBar.setEnabled(True)
        MainWindow.addToolBar(Qt.TopToolBarArea, self.general_utility_toolBar)
        self.graphical_toolBar = QToolBar(MainWindow)
        self.graphical_toolBar.setObjectName(u"graphical_toolBar")
        MainWindow.addToolBar(Qt.LeftToolBarArea, self.graphical_toolBar)
        self.dockWidget = QDockWidget(MainWindow)
        self.dockWidget.setObjectName(u"dockWidget")
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QSize(270, 427))
        self.dockWidget.setMaximumSize(QSize(524287, 524287))
        self.dockWidget.setAutoFillBackground(True)
        self.dockWidget.setAllowedAreas(Qt.LeftDockWidgetArea|Qt.RightDockWidgetArea)
        self.dockWidgetContents = QWidget()
        self.dockWidgetContents.setObjectName(u"dockWidgetContents")
        self.dockWidgetContents.setMinimumSize(QSize(260, 0))
        self.verticalLayout_2 = QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.propertyTab = QTabWidget(self.dockWidgetContents)
        self.propertyTab.setObjectName(u"propertyTab")
        sizePolicy.setHeightForWidth(self.propertyTab.sizePolicy().hasHeightForWidth())
        self.propertyTab.setSizePolicy(sizePolicy)
        self.propertyTab.setMaximumSize(QSize(16777215, 16777215))
        self.propertyTab.setTabPosition(QTabWidget.South)
        self.propertyTab.setTabBarAutoHide(True)
        self.DetailsTab = QWidget()
        self.DetailsTab.setObjectName(u"DetailsTab")
        self.verticalLayout_3 = QVBoxLayout(self.DetailsTab)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.label = QLabel(self.DetailsTab)
        self.label.setObjectName(u"label")
        self.label.setAutoFillBackground(True)

        self.verticalLayout_3.addWidget(self.label)

        self.nodeDetails = QTableView(self.DetailsTab)
        self.nodeDetails.setObjectName(u"nodeDetails")

        self.verticalLayout_3.addWidget(self.nodeDetails)

        self.label_2 = QLabel(self.DetailsTab)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setAutoFillBackground(True)

        self.verticalLayout_3.addWidget(self.label_2)

        self.edgeDetails = QTableView(self.DetailsTab)
        self.edgeDetails.setObjectName(u"edgeDetails")

        self.verticalLayout_3.addWidget(self.edgeDetails)

        self.propertyTab.addTab(self.DetailsTab, "")
        self.HistoryTab = QWidget()
        self.HistoryTab.setObjectName(u"HistoryTab")
        self.verticalLayout = QVBoxLayout(self.HistoryTab)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.undoView = QUndoView(self.HistoryTab)
        self.undoView.setObjectName(u"undoView")
        self.undoView.setMinimumSize(QSize(0, 0))
        self.undoView.setMaximumSize(QSize(265, 16777215))

        self.verticalLayout.addWidget(self.undoView)

        self.propertyTab.addTab(self.HistoryTab, "")

        self.verticalLayout_2.addWidget(self.propertyTab)

        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(Qt.RightDockWidgetArea, self.dockWidget)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuMode.menuAction())
        self.menubar.addAction(self.menuWinodws.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.menuRecent_File.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_Image)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionImportData)
        self.menuFile.addAction(self.actionOutputData)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClose)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuRecent_File.addAction(self.actionFlie_List)
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addAction(self.actionDelete)
        self.menuSettings.addAction(self.menuDraw_Tools.menuAction())
        self.menuSettings.addSeparator()
        self.menuSettings.addAction(self.actionPen_Thickness)
        self.menuSettings.addAction(self.actionPen_Color)
        self.menuSettings.addAction(self.actionBackground_Color)
        self.menuSettings.addAction(self.actionAccent_Color)
        self.menuSettings.addAction(self.actionProperty_And_History)
        self.menuSettings.addAction(self.actionHide_ToolBar)
        self.menuSettings.addAction(self.actionHideControlPoint)
        self.menuDraw_Tools.addAction(self.actionArc)
        self.menuDraw_Tools.addAction(self.actionCircle)
        self.menuDraw_Tools.addAction(self.actionAdd_Annotation)
        self.menuTools.addAction(self.menuShow_Weight.menuAction())
        self.menuTools.addAction(self.menuPathway.menuAction())
        self.menuTools.addAction(self.menuLoop.menuAction())
        self.menuTools.addAction(self.menuGraph_Matrix.menuAction())
        self.menuTools.addAction(self.actionShortestPath)
        self.menuTools.addAction(self.actionConnectivity)
        self.menuTools.addAction(self.actionCompleteGraph)
        self.menuTools.addAction(self.actionMultipleOrSimple)
        self.menuLoop.addAction(self.actionEasy_Loop)
        self.menuLoop.addAction(self.actionPrimary_Loop)
        self.menuGraph_Matrix.addAction(self.actionIncidence_Matrix_Undigraph)
        self.menuGraph_Matrix.addAction(self.menu.menuAction())
        self.menuGraph_Matrix.addAction(self.actionReachable_Matrix)
        self.menu.addAction(self.actionWeight)
        self.menu.addAction(self.action_EdgeNum)
        self.menuPathway.addAction(self.actionEasy_Pathway)
        self.menuPathway.addAction(self.actionPrimary_Pathway)
        self.menuShow_Weight.addAction(self.actionShowNodesWeight)
        self.menuShow_Weight.addAction(self.actionShowEdgesWeight)
        self.menuMode.addAction(self.actionRedigraph_Mode)
        self.menuMode.addAction(self.actionDigraph_Mode)
        self.menuWinodws.addAction(self.actionMinimise)
        self.menuWinodws.addAction(self.actionMaximize)
        self.menuWinodws.addAction(self.actionMini_Mode)
        self.menuWinodws.addAction(self.menuLanguage.menuAction())
        self.menuLanguage.addAction(self.actionSetEnglish)
        self.menuLanguage.addAction(self.actionSetChinese)
        self.menuHelp.addAction(self.actionConnect_Author)
        self.menuHelp.addAction(self.actionWelcome)
        self.menuHelp.addAction(self.actionHelp_Document)
        self.general_utility_toolBar.addAction(self.actionNew)
        self.general_utility_toolBar.addAction(self.actionOpen)
        self.general_utility_toolBar.addAction(self.actionSave)
        self.general_utility_toolBar.addAction(self.actionUndo)
        self.general_utility_toolBar.addAction(self.actionRedo)
        self.general_utility_toolBar.addAction(self.actionDelete)
        self.general_utility_toolBar.addSeparator()
        self.general_utility_toolBar.addAction(self.actionPen_Color)
        self.general_utility_toolBar.addAction(self.actionPen_Thickness)
        self.general_utility_toolBar.addAction(self.actionBackground_Color)
        self.general_utility_toolBar.addAction(self.actionAccent_Color)
        self.graphical_toolBar.addAction(self.actionArc)
        self.graphical_toolBar.addAction(self.actionCircle)
        self.graphical_toolBar.addAction(self.actionAdd_Annotation)

        self.retranslateUi(MainWindow)
        self.actionHide_ToolBar.toggled.connect(self.general_utility_toolBar.setVisible)
        self.actionHide_ToolBar.toggled.connect(self.graphical_toolBar.setVisible)
        self.actionMinimise.triggered.connect(MainWindow.showMinimized)
        self.actionMaximize.triggered.connect(MainWindow.showMaximized)
        self.actionProperty_And_History.toggled.connect(self.dockWidget.setVisible)
        self.actionQuit.triggered.connect(MainWindow.close)

        self.propertyTab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.actionNew.setToolTip(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionNew.setStatusTip(QCoreApplication.translate("MainWindow", u"\u65b0\u5efa\u6587\u4ef6", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.actionOpen.setToolTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionOpen.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6253\u5f00\u6587\u4ef6", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionOpen.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58", None))
#if QT_CONFIG(tooltip)
        self.actionSave.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave.setStatusTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6587\u4ef6", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_As.setText(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a", None))
#if QT_CONFIG(tooltip)
        self.actionSave_As.setToolTip(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave_As.setStatusTip(QCoreApplication.translate("MainWindow", u"\u53e6\u5b58\u4e3a", None))
#endif // QT_CONFIG(statustip)
        self.actionSave_All.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u5168\u90e8", None))
#if QT_CONFIG(tooltip)
        self.actionSave_All.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u5168\u90e8", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave_All.setStatusTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u6240\u6709", None))
#endif // QT_CONFIG(statustip)
        self.actionImportData.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u6570\u636e", None))
#if QT_CONFIG(tooltip)
        self.actionImportData.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bfc\u5165\u6570\u636e", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionImportData.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u56fe\u6570\u636e", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionImportData.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionOutputData.setText(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u6570\u636e", None))
#if QT_CONFIG(tooltip)
        self.actionOutputData.setToolTip(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u6570\u636e", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionOutputData.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5bfc\u51fa\u56fe\u6570\u636e", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionOutputData.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_Image.setText(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u4e3a\u56fe\u7247", None))
#if QT_CONFIG(tooltip)
        self.actionSave_Image.setToolTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u4e3a\u56fe\u7247", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionSave_Image.setStatusTip(QCoreApplication.translate("MainWindow", u"\u4fdd\u5b58\u4e3a\u56fe\u7247", None))
#endif // QT_CONFIG(statustip)
        self.actionClose.setText(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.actionClose.setToolTip(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionClose.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5173\u95ed\u5f53\u524d\u7a97\u53e3", None))
#endif // QT_CONFIG(statustip)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"\u9000\u51fa\u5e94\u7528", None))
#if QT_CONFIG(tooltip)
        self.actionQuit.setToolTip(QCoreApplication.translate("MainWindow", u"\u9000\u51fa\u5e94\u7528", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionQuit.setStatusTip(QCoreApplication.translate("MainWindow", u"\u9000\u51fa\u5e94\u7528\u7a0b\u5e8f", None))
#endif // QT_CONFIG(statustip)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"\u64a4\u9500", None))
#if QT_CONFIG(tooltip)
        self.actionUndo.setToolTip(QCoreApplication.translate("MainWindow", u"\u64a4\u9500", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionUndo.setStatusTip(QCoreApplication.translate("MainWindow", u"\u9000\u56de\u4e0a\u4e00\u6b65", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
#if QT_CONFIG(tooltip)
        self.actionRedo.setToolTip(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionRedo.setStatusTip(QCoreApplication.translate("MainWindow", u"\u91cd\u505a", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionDelete.setText(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
#if QT_CONFIG(tooltip)
        self.actionDelete.setToolTip(QCoreApplication.translate("MainWindow", u"\u5220\u9664", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionDelete.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5220\u9664\u5f53\u524d\u6240\u9009\u56fe\u5143", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionDelete.setShortcut(QCoreApplication.translate("MainWindow", u"Del", None))
#endif // QT_CONFIG(shortcut)
        self.actionFind.setText(QCoreApplication.translate("MainWindow", u"\u67e5\u627e", None))
#if QT_CONFIG(tooltip)
        self.actionFind.setToolTip(QCoreApplication.translate("MainWindow", u"\u67e5\u627e", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionFind.setStatusTip(QCoreApplication.translate("MainWindow", u"\u67e5\u627e\u56fe\u5143", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionFind.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionReplace.setText(QCoreApplication.translate("MainWindow", u"\u66ff\u6362", None))
#if QT_CONFIG(tooltip)
        self.actionReplace.setToolTip(QCoreApplication.translate("MainWindow", u"\u66ff\u6362", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionReplace.setStatusTip(QCoreApplication.translate("MainWindow", u"\u66ff\u6362\u56fe\u5143", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(shortcut)
        self.actionReplace.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionEasy_Pathway.setText(QCoreApplication.translate("MainWindow", u"\u7b80\u5355\u901a\u8def", None))
#if QT_CONFIG(tooltip)
        self.actionEasy_Pathway.setToolTip(QCoreApplication.translate("MainWindow", u"\u7b80\u5355\u901a\u8def", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionEasy_Pathway.setStatusTip(QCoreApplication.translate("MainWindow", u"\u901a\u8def\u4e2d\u7684\u8fb9\u4e92\u4e0d\u76f8\u540c\uff0c\u5219\u79f0\u5176\u4e3a\u00a3\u7684\u7b80\u5355\u901a\u8def", None))
#endif // QT_CONFIG(statustip)
        self.actionEasy_Loop.setText(QCoreApplication.translate("MainWindow", u"\u7b80\u5355\u56de\u8def", None))
#if QT_CONFIG(tooltip)
        self.actionEasy_Loop.setToolTip(QCoreApplication.translate("MainWindow", u"\u7b80\u5355\u56de\u8def", None))
#endif // QT_CONFIG(tooltip)
        self.actionIncidence_Matrix_Undigraph.setText(QCoreApplication.translate("MainWindow", u"\u5173\u8054\u77e9\u9635", None))
#if QT_CONFIG(tooltip)
        self.actionIncidence_Matrix_Undigraph.setToolTip(QCoreApplication.translate("MainWindow", u"\u5173\u8054\u77e9\u9635", None))
#endif // QT_CONFIG(tooltip)
        self.actionCritical_Path.setText(QCoreApplication.translate("MainWindow", u"\u5173\u952e\u8def\u5f84", None))
#if QT_CONFIG(tooltip)
        self.actionCritical_Path.setToolTip(QCoreApplication.translate("MainWindow", u"\u5173\u952e\u8def\u5f84", None))
#endif // QT_CONFIG(tooltip)
        self.actionGraph_Coloring_Problem.setText(QCoreApplication.translate("MainWindow", u"\u7740\u8272\u95ee\u9898", None))
#if QT_CONFIG(tooltip)
        self.actionGraph_Coloring_Problem.setToolTip(QCoreApplication.translate("MainWindow", u"\u7740\u8272\u95ee\u9898", None))
#endif // QT_CONFIG(tooltip)
        self.actionDigraph_Mode.setText(QCoreApplication.translate("MainWindow", u"\u6709\u5411\u56fe\u6a21\u5f0f", None))
#if QT_CONFIG(tooltip)
        self.actionDigraph_Mode.setToolTip(QCoreApplication.translate("MainWindow", u"\u6709\u5411\u56fe\u6a21\u5f0f", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionDigraph_Mode.setShortcut(QCoreApplication.translate("MainWindow", u"F1", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedigraph_Mode.setText(QCoreApplication.translate("MainWindow", u"\u65e0\u5411\u56fe\u6a21\u5f0f", None))
#if QT_CONFIG(tooltip)
        self.actionRedigraph_Mode.setToolTip(QCoreApplication.translate("MainWindow", u"\u65e0\u5411\u56fe\u6a21\u5f0f", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(shortcut)
        self.actionRedigraph_Mode.setShortcut(QCoreApplication.translate("MainWindow", u"F2", None))
#endif // QT_CONFIG(shortcut)
        self.actionMinimise.setText(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3\u6700\u5c0f\u5316", None))
#if QT_CONFIG(tooltip)
        self.actionMinimise.setToolTip(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3\u6700\u5c0f\u5316", None))
#endif // QT_CONFIG(tooltip)
        self.actionMaximize.setText(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3\u6700\u5927\u5316", None))
#if QT_CONFIG(tooltip)
        self.actionMaximize.setToolTip(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3\u6700\u5927\u5316", None))
#endif // QT_CONFIG(tooltip)
        self.actionMini_Mode.setText(QCoreApplication.translate("MainWindow", u"\u8ff7\u4f60\u6a21\u5f0f", None))
#if QT_CONFIG(tooltip)
        self.actionMini_Mode.setToolTip(QCoreApplication.translate("MainWindow", u"\u8ff7\u4f60\u6a21\u5f0f", None))
#endif // QT_CONFIG(tooltip)
        self.actionHide_ToolBar.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u5de5\u5177\u680f", None))
#if QT_CONFIG(tooltip)
        self.actionHide_ToolBar.setToolTip(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u4e0e\u9690\u85cf\u5de5\u5177\u680f", None))
#endif // QT_CONFIG(tooltip)
        self.actionConnect_Author.setText(QCoreApplication.translate("MainWindow", u"\u8054\u7cfb\u4f5c\u8005", None))
#if QT_CONFIG(tooltip)
        self.actionConnect_Author.setToolTip(QCoreApplication.translate("MainWindow", u"\u8054\u7cfb\u4f5c\u8005", None))
#endif // QT_CONFIG(tooltip)
        self.actionWelcome.setText(QCoreApplication.translate("MainWindow", u"\u6b22\u8fce", None))
#if QT_CONFIG(tooltip)
        self.actionWelcome.setToolTip(QCoreApplication.translate("MainWindow", u"\u6b22\u8fce", None))
#endif // QT_CONFIG(tooltip)
        self.actionHelp_Document.setText(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9\u6587\u6863", None))
#if QT_CONFIG(tooltip)
        self.actionHelp_Document.setToolTip(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9\u6587\u6863", None))
#endif // QT_CONFIG(tooltip)
        self.actionFlie_List.setText(QCoreApplication.translate("MainWindow", u"\u6700\u8fd1\u6587\u4ef6", None))
#if QT_CONFIG(tooltip)
        self.actionFlie_List.setToolTip(QCoreApplication.translate("MainWindow", u"\u6700\u8fd1\u6587\u4ef6", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionFlie_List.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6700\u8fd1\u6253\u5f00\u7684\u6587\u4ef6", None))
#endif // QT_CONFIG(statustip)
        self.actionPen_Thickness.setText(QCoreApplication.translate("MainWindow", u"\u753b\u7b14\u7c97\u7ec6\u4e0e\u6837\u5f0f", None))
#if QT_CONFIG(tooltip)
        self.actionPen_Thickness.setToolTip(QCoreApplication.translate("MainWindow", u"\u753b\u7b14\u7c97\u7ec6\u4e0e\u6837\u5f0f", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionPen_Thickness.setStatusTip(QCoreApplication.translate("MainWindow", u"\u8c03\u6574\u753b\u7b14\u7c97\u7ec6\u4e0e\u6837\u5f0f", None))
#endif // QT_CONFIG(statustip)
        self.actionPen_Color.setText(QCoreApplication.translate("MainWindow", u"\u753b\u7b14\u989c\u8272", None))
#if QT_CONFIG(tooltip)
        self.actionPen_Color.setToolTip(QCoreApplication.translate("MainWindow", u"\u753b\u7b14\u989c\u8272", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionPen_Color.setStatusTip(QCoreApplication.translate("MainWindow", u"\u8c03\u6574\u753b\u7b14\u7684\u989c\u8272", None))
#endif // QT_CONFIG(statustip)
        self.actionBackground_Color.setText(QCoreApplication.translate("MainWindow", u"\u80cc\u666f\u8272", None))
#if QT_CONFIG(tooltip)
        self.actionBackground_Color.setToolTip(QCoreApplication.translate("MainWindow", u"\u80cc\u666f\u8272", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionBackground_Color.setStatusTip(QCoreApplication.translate("MainWindow", u"\u8c03\u6574\u753b\u677f\u7684\u80cc\u666f\u8272", None))
#endif // QT_CONFIG(statustip)
        self.actionArc.setText(QCoreApplication.translate("MainWindow", u"\u8fb9", None))
#if QT_CONFIG(tooltip)
        self.actionArc.setToolTip(QCoreApplication.translate("MainWindow", u"\u66f2\u7ebf", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionArc.setStatusTip(QCoreApplication.translate("MainWindow", u"\u7ed8\u56fe\u6240\u4f7f\u7528\u7684\u8fb9", None))
#endif // QT_CONFIG(statustip)
        self.actionCircle.setText(QCoreApplication.translate("MainWindow", u"\u9876\u70b9", None))
#if QT_CONFIG(tooltip)
        self.actionCircle.setToolTip(QCoreApplication.translate("MainWindow", u"\u7ed3\u70b9", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionCircle.setStatusTip(QCoreApplication.translate("MainWindow", u"\u7ed8\u56fe\u6240\u4f7f\u7528\u7684\u9876\u70b9", None))
#endif // QT_CONFIG(statustip)
        self.actionSetEnglish.setText(QCoreApplication.translate("MainWindow", u"English", None))
        self.actionSetChinese.setText(QCoreApplication.translate("MainWindow", u"\u4e2d\u6587", None))
#if QT_CONFIG(tooltip)
        self.actionSetChinese.setToolTip(QCoreApplication.translate("MainWindow", u"\u4e2d\u6587", None))
#endif // QT_CONFIG(tooltip)
        self.actionAdd_Annotation.setText(QCoreApplication.translate("MainWindow", u"\u6ce8\u91ca", None))
#if QT_CONFIG(tooltip)
        self.actionAdd_Annotation.setToolTip(QCoreApplication.translate("MainWindow", u"\u6dfb\u52a0\u6ce8\u91ca", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionAdd_Annotation.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5411\u56fe\u4e2d\u6dfb\u52a0\u6ce8\u91ca", None))
#endif // QT_CONFIG(statustip)
        self.actionProperty_And_History.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u5c5e\u6027\u4e0e\u5386\u53f2\u8bb0\u5f55", None))
#if QT_CONFIG(tooltip)
        self.actionProperty_And_History.setToolTip(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u4e0e\u9690\u85cf\u5c5e\u6027\u4e0e\u5386\u53f2\u8bb0\u5f55", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionProperty_And_History.setStatusTip(QCoreApplication.translate("MainWindow", u"\u9690\u85cf\u6216\u8005\u663e\u793a\u5c5e\u6027\u680f", None))
#endif // QT_CONFIG(statustip)
        self.actionAccent_Color.setText(QCoreApplication.translate("MainWindow", u"\u9009\u4e2d\u8272", None))
#if QT_CONFIG(tooltip)
        self.actionAccent_Color.setToolTip(QCoreApplication.translate("MainWindow", u"\u56fe\u5143\u9009\u4e2d\u8272", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.actionAccent_Color.setStatusTip(QCoreApplication.translate("MainWindow", u"\u9009\u4e2d\u56fe\u539f\u65f6\u7684\u989c\u8272", None))
#endif // QT_CONFIG(statustip)
        self.actionReachable_Matrix.setText(QCoreApplication.translate("MainWindow", u"\u53ef\u8fbe\u77e9\u9635", None))
        self.actionPrimary_Pathway.setText(QCoreApplication.translate("MainWindow", u"\u521d\u7ea7\u901a\u8def", None))
        self.actionPrimary_Loop.setText(QCoreApplication.translate("MainWindow", u"\u521d\u7ea7\u56de\u8def", None))
        self.actionShortestPath.setText(QCoreApplication.translate("MainWindow", u"\u6700\u77ed\u8def\u5f84", None))
        self.actionWeight.setText(QCoreApplication.translate("MainWindow", u"\u5143\u7d20\u4e3a\u6743\u91cd", None))
        self.action_EdgeNum.setText(QCoreApplication.translate("MainWindow", u"\u5143\u7d20\u4e3a\u8fb9\u6570", None))
        self.actionConnectivity.setText(QCoreApplication.translate("MainWindow", u"\u56fe\u7684\u8fde\u901a\u6027", None))
        self.actionCompleteGraph.setText(QCoreApplication.translate("MainWindow", u"\u5b8c\u5168\u56fe\u5224\u5b9a", None))
        self.actionMultipleOrSimple.setText(QCoreApplication.translate("MainWindow", u"\u7b80\u5355\u56fe\u591a\u91cd\u56fe\u5224\u5b9a", None))
        self.actionShowNodesWeight.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u9876\u70b9\u6743\u91cd", None))
        self.actionShowEdgesWeight.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u8fb9\u6743\u91cd", None))
        self.actionHideControlPoint.setText(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u63a7\u5236\u70b9", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Page), QCoreApplication.translate("MainWindow", u"\u753b\u677f1", None))
#if QT_CONFIG(statustip)
        self.menuFile.setStatusTip(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6\u64cd\u4f5c", None))
#endif // QT_CONFIG(statustip)
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"\u6587\u4ef6", None))
        self.menuRecent_File.setTitle(QCoreApplication.translate("MainWindow", u"\u6700\u8fd1\u6253\u5f00\u7684\u6587\u4ef6", None))
#if QT_CONFIG(statustip)
        self.menuEdit.setStatusTip(QCoreApplication.translate("MainWindow", u"\u5e38\u7528\u7684\u64cd\u4f5c", None))
#endif // QT_CONFIG(statustip)
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"\u7f16\u8f91", None))
#if QT_CONFIG(statustip)
        self.menuSettings.setStatusTip(QCoreApplication.translate("MainWindow", u"\u7ed8\u56fe\u5de5\u5177\u548c\u7ed8\u56fe\u677f\u76f8\u5173\u8bbe\u7f6e", None))
#endif // QT_CONFIG(statustip)
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"\u8bbe\u7f6e", None))
#if QT_CONFIG(statustip)
        self.menuDraw_Tools.setStatusTip(QCoreApplication.translate("MainWindow", u"\u7ed8\u56fe\u5de5\u5177", None))
#endif // QT_CONFIG(statustip)
        self.menuDraw_Tools.setTitle(QCoreApplication.translate("MainWindow", u"\u7ed8\u56fe\u5de5\u5177", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"\u5de5\u5177", None))
#if QT_CONFIG(statustip)
        self.menuLoop.setStatusTip(QCoreApplication.translate("MainWindow", u"\u7ed9\u5b9a\u56feG=<V,E>\uff08\u65e0\u5411\u56fe\u6216\u6709\u5411\u56fe\uff09, G\u4e2d\u9876\u70b9\u4e0e\u8fb9\u7684\u4ea4\u66ff\u5e8f\u5217\u00a3=v0e1v1e2\u2026envn. \u5176\u4e2d1<=i<=n, ei=(vi-1,vi), \u5219\u79f0\u00a3\u4e3av0\u5230vn\u7684\u901a\u8def\u3002v0\u548cvn\u5206\u522b\u4e3a\u901a\u8def\u7684\u8d77\u70b9\u548c\u7ec8\u70b9, n(\u8fb9\u7684\u6761\u6570)\u4e3a\u901a\u8def\u7684\u957f\u5ea6\uff0c \u5f53v0=vn\u65f6\uff0c\u5219\u79f0\u5176\u4e3a\u56de\u8def", None))
#endif // QT_CONFIG(statustip)
        self.menuLoop.setTitle(QCoreApplication.translate("MainWindow", u"\u56de\u8def", None))
        self.menuGraph_Matrix.setTitle(QCoreApplication.translate("MainWindow", u"\u56fe\u7684\u77e9\u9635", None))
        self.menu.setTitle(QCoreApplication.translate("MainWindow", u"\u90bb\u63a5\u77e9\u9635", None))
#if QT_CONFIG(statustip)
        self.menuPathway.setStatusTip(QCoreApplication.translate("MainWindow", u"\u56fe\u7684\u901a\u8def\uff0c\u5b9a\u4e49\u67e5\u770b\uff08Shift+F1\uff09", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.menuPathway.setWhatsThis(QCoreApplication.translate("MainWindow", u"\u7ed9\u5b9a\u56feG=<V,E>\uff08\u65e0\u5411\u56fe\u6216\u6709\u5411\u56fe\uff09, G\u4e2d\u9876\u70b9\u4e0e\u8fb9\u7684\u4ea4\u66ff\u5e8f\u5217\u00a3=v0e1v1e2\u2026envn. \u5176\u4e2d1<=i<=n, ei=(vi-1,vi), \u5219\u79f0\u00a3\u4e3av0\u5230vn\u7684\u901a\u8def\u3002v0\u548cvn\u5206\u522b\u4e3a\u901a\u8def\u7684\u8d77\u70b9\u548c\u7ec8\u70b9, n(\u8fb9\u7684\u6761\u6570)\u4e3a\u901a\u8def\u7684\u957f\u5ea6\u3002", None))
#endif // QT_CONFIG(whatsthis)
        self.menuPathway.setTitle(QCoreApplication.translate("MainWindow", u"\u901a\u8def", None))
        self.menuShow_Weight.setTitle(QCoreApplication.translate("MainWindow", u"\u663e\u793a\u6743\u91cd", None))
        self.menuMode.setTitle(QCoreApplication.translate("MainWindow", u"\u6a21\u5f0f", None))
        self.menuWinodws.setTitle(QCoreApplication.translate("MainWindow", u"\u7a97\u53e3", None))
        self.menuLanguage.setTitle(QCoreApplication.translate("MainWindow", u"\u8bed\u8a00", None))
        self.menuHelp.setTitle(QCoreApplication.translate("MainWindow", u"\u5e2e\u52a9", None))
        self.general_utility_toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u5e38\u89c4\u529f\u80fd", None))
        self.graphical_toolBar.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u7ed8\u56fe\u5de5\u5177", None))
        self.dockWidget.setWindowTitle(QCoreApplication.translate("MainWindow", u"\u5c5e\u6027", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u9876\u70b9\u8be6\u60c5", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u8fb9\u8be6\u60c5", None))
        self.propertyTab.setTabText(self.propertyTab.indexOf(self.DetailsTab), QCoreApplication.translate("MainWindow", u"\u7ed8\u56fe\u8be6\u60c5", None))
        self.propertyTab.setTabText(self.propertyTab.indexOf(self.HistoryTab), QCoreApplication.translate("MainWindow", u"\u5386\u53f2\u8bb0\u5f55", None))
    # retranslateUi

