# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ThicknessDialog.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ThicknessDialog(object):
    def setupUi(self, ThicknessDialog):
        ThicknessDialog.setObjectName("ThicknessDialog")
        ThicknessDialog.resize(350, 250)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ThicknessDialog.sizePolicy().hasHeightForWidth())
        ThicknessDialog.setSizePolicy(sizePolicy)
        ThicknessDialog.setMinimumSize(QtCore.QSize(350, 250))
        ThicknessDialog.setMaximumSize(QtCore.QSize(350, 250))
        ThicknessDialog.setAutoFillBackground(True)
        self.verticalLayoutWidget = QtWidgets.QWidget(ThicknessDialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 360, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout.setContentsMargins(10, 10, 20, 5)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.rt_thickness = QtWidgets.QWidget(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rt_thickness.sizePolicy().hasHeightForWidth())
        self.rt_thickness.setSizePolicy(sizePolicy)
        self.rt_thickness.setMinimumSize(QtCore.QSize(0, 30))
        self.rt_thickness.setMaximumSize(QtCore.QSize(334, 30))
        self.rt_thickness.setObjectName("rt_thickness")
        self.verticalLayout.addWidget(self.rt_thickness)
        self.penStyleComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.penStyleComboBox.setMinimumSize(QtCore.QSize(330, 36))
        self.penStyleComboBox.setMaximumSize(QtCore.QSize(330, 36))
        self.penStyleComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.penStyleComboBox.setIconSize(QtCore.QSize(180, 30))
        self.penStyleComboBox.setObjectName("penStyleComboBox")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/SolidLine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penStyleComboBox.addItem(icon, "")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/DashLine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penStyleComboBox.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/DotLine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penStyleComboBox.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/DashDotLine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penStyleComboBox.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/DashDotDotLine.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.penStyleComboBox.addItem(icon4, "")
        self.verticalLayout.addWidget(self.penStyleComboBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.thicknessSlider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.thicknessSlider.setMinimum(1)
        self.thicknessSlider.setMaximum(20)
        self.thicknessSlider.setOrientation(QtCore.Qt.Horizontal)
        self.thicknessSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.thicknessSlider.setObjectName("thicknessSlider")
        self.horizontalLayout.addWidget(self.thicknessSlider)
        self.thicknessNumber = QtWidgets.QLCDNumber(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thicknessNumber.sizePolicy().hasHeightForWidth())
        self.thicknessNumber.setSizePolicy(sizePolicy)
        self.thicknessNumber.setMaximumSize(QtCore.QSize(64, 66))
        self.thicknessNumber.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.thicknessNumber.setAutoFillBackground(True)
        self.thicknessNumber.setProperty("value", 1.0)
        self.thicknessNumber.setObjectName("thicknessNumber")
        self.horizontalLayout.addWidget(self.thicknessNumber)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnOk = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout_2.addWidget(self.btnOk)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.btnCancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ThicknessDialog)
        self.btnOk.clicked.connect(ThicknessDialog.accept)
        self.btnCancel.clicked.connect(ThicknessDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ThicknessDialog)

    def retranslateUi(self, ThicknessDialog):
        _translate = QtCore.QCoreApplication.translate
        ThicknessDialog.setWindowTitle(_translate("ThicknessDialog", "Dialog"))
        self.penStyleComboBox.setItemText(0, _translate("ThicknessDialog", "SolidLine"))
        self.penStyleComboBox.setItemText(1, _translate("ThicknessDialog", "DashLine"))
        self.penStyleComboBox.setItemText(2, _translate("ThicknessDialog", "DotLine"))
        self.penStyleComboBox.setItemText(3, _translate("ThicknessDialog", "DashDotLine"))
        self.penStyleComboBox.setItemText(4, _translate("ThicknessDialog", "DashDotDotLine"))
        self.btnOk.setText(_translate("ThicknessDialog", "OK"))
        self.btnCancel.setText(_translate("ThicknessDialog", "Cancel"))
import res_rc
